{"name": "Cancelar exclusão de um usuário", "status": "failed", "statusDetails": {"message": "AssertionError: Erro ao cancelar a exclusão do usuário 'Nome Editado': elemento não encontrado ou não clicável.\n", "trace": "  File \"C:\\Users\\mferreio\\AppData\\Local\\Programs\\Python\\Python312\\Lib\\site-packages\\behave\\model.py\", line 1329, in run\n    match.run(runner.context)\n  File \"C:\\Users\\mferreio\\AppData\\Local\\Programs\\Python\\Python312\\Lib\\site-packages\\behave\\matchers.py\", line 98, in run\n    self.func(context, *args, **kwargs)\n  File \"features\\steps\\test_tela_de_usuarios_steps.py\", line 152, in step_clicar_botao_exclui_usuario\n    context.tela_de_usuarios_page.cancelar_exclusao_de_usuario(EXCLUIR_NOME)\n  File \"C:\\Users\\mferreio\\OneDrive - NTT DATA EMEAL\\Documents\\__Github_Projetos__\\AutomacaoDeTeste\\features\\pages\\tela_de_usuarios_pages.py\", line 295, in cancelar_exclusao_de_usuario\n    raise AssertionError(f\"Erro ao cancelar a exclusão do usuário '{excluir_nome}': elemento não encontrado ou não clicável.\")\n"}, "steps": [{"name": "Iniciando cenário: Cancelar exclusão de um usuário", "status": "passed", "start": 1743100275286, "stop": 1743100275286}, {"name": "Given que o usuário está logado como \"Administrador\"", "status": "passed", "steps": [{"name": "Iniciando passo: que o usuário está logado como \"Administrador\"", "status": "passed", "start": 1743100275287, "stop": 1743100275287}, {"name": "Validando que o usuário está logado como Administrador", "status": "passed", "parameters": [{"name": "context", "value": "<behave.runner.Context object at 0x000001C024ADBF80>"}], "start": 1743100275287, "stop": 1743100275295}], "start": 1743100275287, "stop": 1743100275428}, {"name": "When navega até a tela de usuários - Perfil", "status": "passed", "steps": [{"name": "Iniciando passo: navega até a tela de usuários - Perfil", "status": "passed", "start": 1743100275429, "stop": 1743100275429}, {"name": "Navegando até a tela de usuários - Perfil", "status": "passed", "parameters": [{"name": "context", "value": "<behave.runner.Context object at 0x000001C024ADBF80>"}], "start": 1743100275429, "stop": 1743100277493}], "start": 1743100275429, "stop": 1743100277638}, {"name": "When pesquisa um usuario cadastrado", "status": "passed", "steps": [{"name": "Iniciando passo: pesquisa um usuario cadastrado", "status": "passed", "start": 1743100277638, "stop": 1743100277638}], "start": 1743100277638, "stop": 1743100281930}, {"name": "When clica em excluir e cancela a exclusao", "status": "failed", "statusDetails": {"message": "AssertionError: Erro ao cancelar a exclusão do usuário 'Nome Editado': elemento não encontrado ou não clicável.\n", "trace": "  File \"C:\\Users\\mferreio\\AppData\\Local\\Programs\\Python\\Python312\\Lib\\site-packages\\behave\\model.py\", line 1329, in run\n    match.run(runner.context)\n  File \"C:\\Users\\mferreio\\AppData\\Local\\Programs\\Python\\Python312\\Lib\\site-packages\\behave\\matchers.py\", line 98, in run\n    self.func(context, *args, **kwargs)\n  File \"features\\steps\\test_tela_de_usuarios_steps.py\", line 152, in step_clicar_botao_exclui_usuario\n    context.tela_de_usuarios_page.cancelar_exclusao_de_usuario(EXCLUIR_NOME)\n  File \"C:\\Users\\mferreio\\OneDrive - NTT DATA EMEAL\\Documents\\__Github_Projetos__\\AutomacaoDeTeste\\features\\pages\\tela_de_usuarios_pages.py\", line 295, in cancelar_exclusao_de_usuario\n    raise AssertionError(f\"Erro ao cancelar a exclusão do usuário '{excluir_nome}': elemento não encontrado ou não clicável.\")\n"}, "steps": [{"name": "Iniciando passo: clica em excluir e cancela a exclusao", "status": "passed", "start": 1743100281931, "stop": 1743100281931}], "attachments": [{"name": "clica em excluir e cancela a exclusao", "source": "cadc0660-c75e-4975-b7e8-706b632ef20f-attachment.png", "type": "image/png"}], "start": 1743100281931, "stop": 1743100294821}, {"name": "Then navega até a tela de usuários - Perfil", "status": "skipped", "start": 1743100294825, "stop": 1743100294825}], "attachments": [{"name": "Detalhes do Cenário", "source": "5b6e826f-1ce9-4c0d-84bc-b58aeb5ce51f-attachment.txt", "type": "text/plain"}], "start": 1743100275285, "stop": 1743100294825, "uuid": "79ae2619-a34b-47d9-891a-4c4b7b5322cd", "historyId": "decee6f137a95e1aaec409ffb75b4692", "fullName": "Acessar a página de login e testar fluxo de tela de usuários: Cancelar exclusão de um usuário", "labels": [{"name": "severity", "value": "normal"}, {"name": "feature", "value": "Acessar a página de login e testar fluxo de tela de usuários"}, {"name": "framework", "value": "behave"}, {"name": "language", "value": "cpython3"}]}