{"name": "Cancelar exclusão de um usuário", "status": "failed", "statusDetails": {"message": "AssertionError: Erro ao cancelar a exclusão do usuário 'Editado Teste da SilvaE975263  A02458719a*': elemento não encontrado ou não clicável.\n", "trace": "  File \"C:\\Users\\mferreio\\AppData\\Local\\Programs\\Python\\Python312\\Lib\\site-packages\\behave\\model.py\", line 1329, in run\n    match.run(runner.context)\n  File \"C:\\Users\\mferreio\\AppData\\Local\\Programs\\Python\\Python312\\Lib\\site-packages\\behave\\matchers.py\", line 98, in run\n    self.func(context, *args, **kwargs)\n  File \"features\\steps\\test_tela_de_usuarios_steps.py\", line 149, in step_clicar_botao_exclui_usuario\n    context.tela_de_usuarios_page.cancelar_exclusao_de_usuario(EXCLUIR_NOME)\n  File \"C:\\Users\\mferreio\\OneDrive - NTT DATA EMEAL\\Documents\\__Github_Projetos__\\neo_liberalizados-automacao\\features\\pages\\tela_de_usuarios_pages.py\", line 295, in cancelar_exclusao_de_usuario\n    raise AssertionError(f\"Erro ao cancelar a exclusão do usuário '{excluir_nome}': elemento não encontrado ou não clicável.\")\n"}, "steps": [{"name": "Given que o usuário está logado como \"Administrador\"", "status": "passed", "steps": [{"name": "Validando que o usuário está logado como Administrador", "status": "passed", "parameters": [{"name": "context", "value": "<behave.runner.Context object at 0x0000019510B19430>"}], "start": 1744031883286, "stop": 1744031883301}], "start": 1744031883285, "stop": 1744031883301}, {"name": "When navega até a tela de usuários - Perfil", "status": "passed", "steps": [{"name": "Navegando até a tela de usuários - Perfil", "status": "passed", "parameters": [{"name": "context", "value": "<behave.runner.Context object at 0x0000019510B19430>"}], "start": 1744031883302, "stop": 1744031885394}], "start": 1744031883301, "stop": 1744031885394}, {"name": "When pesquisa um usuario cadastrado", "status": "passed", "start": 1744031885394, "stop": 1744031889739}, {"name": "When clica em excluir e cancela a exclusao", "status": "failed", "statusDetails": {"message": "AssertionError: Erro ao cancelar a exclusão do usuário 'Editado Teste da SilvaE975263  A02458719a*': elemento não encontrado ou não clicável.\n", "trace": "  File \"C:\\Users\\mferreio\\AppData\\Local\\Programs\\Python\\Python312\\Lib\\site-packages\\behave\\model.py\", line 1329, in run\n    match.run(runner.context)\n  File \"C:\\Users\\mferreio\\AppData\\Local\\Programs\\Python\\Python312\\Lib\\site-packages\\behave\\matchers.py\", line 98, in run\n    self.func(context, *args, **kwargs)\n  File \"features\\steps\\test_tela_de_usuarios_steps.py\", line 149, in step_clicar_botao_exclui_usuario\n    context.tela_de_usuarios_page.cancelar_exclusao_de_usuario(EXCLUIR_NOME)\n  File \"C:\\Users\\mferreio\\OneDrive - NTT DATA EMEAL\\Documents\\__Github_Projetos__\\neo_liberalizados-automacao\\features\\pages\\tela_de_usuarios_pages.py\", line 295, in cancelar_exclusao_de_usuario\n    raise AssertionError(f\"Erro ao cancelar a exclusão do usuário '{excluir_nome}': elemento não encontrado ou não clicável.\")\n"}, "start": 1744031889739, "stop": 1744031902392}, {"name": "Then navega até a tela de usuários - Perfil", "status": "skipped", "start": 1744031902393, "stop": 1744031902393}], "start": 1744031883282, "stop": 1744031902393, "uuid": "f484934b-b7c4-4e6f-806b-40d6c0361349", "historyId": "decee6f137a95e1aaec409ffb75b4692", "fullName": "Acessar a página de login e testar fluxo de tela de usuários: Cancelar exclusão de um usuário", "labels": [{"name": "severity", "value": "normal"}, {"name": "feature", "value": "Acessar a página de login e testar fluxo de tela de usuários"}, {"name": "framework", "value": "behave"}, {"name": "language", "value": "cpython3"}]}